version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - goprintffuncname
    - gosec
    - gosmopolitan
    - inamedparam
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - usestdlibvars
    - wastedassign
    - zerologlint
  exclusions:
    presets:
      - comments
    rules:
      - linters:
          - errcheck
          - errchkjson
          - gosec
          - noctx
        path: _test\.go
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/curioswitch/go-build)
