name: Setup Go
description: Setup Go using existing cache
inputs:
  go-version:
    description: The Go version to use. If unset, go.work will be used.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: ${{ !inputs.go-version && 'go.work' || '' }}
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: resolve go environment
      id: goenv
      shell: bash
      run: |
        {
          echo "go_cache=$(go env GOCACHE)"
          echo "go_modcache=$(go env GOMODCACHE)"
          echo "go_version=$(go env GOVERSION)"
        } >> "$GITHUB_OUTPUT"

    - uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: |
          ${{ steps.goenv.outputs.go_modcache }}
          ${{ steps.goenv.outputs.go_cache }}
        key: go-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-${{ hashFiles('**/go.mod', '**/versions.go') }}
        restore-keys: |
          go-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-
          go-${{ runner.os }}-
