name: Setup Go
description: Setup Go using existing cache
inputs:
  go-version:
    description: The Go version to use. If unset, go.work will be used.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: ${{ !inputs.go-version && 'go.work' || '' }}
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: resolve go environment
      id: goenv
      shell: bash
      run: |
        {
          echo "go_cache=$(go env GOCACHE)"
          echo "go_modcache=$(go env GOMODCACHE)"
          echo "go_version=$(go env GOVERSION)"
        } >> "$GITHUB_OUTPUT"

    - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ${{ steps.goenv.outputs.go_modcache }}
          ${{ steps.goenv.outputs.go_cache }}
        key: gomod-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-${{ hashFiles('**/go.mod', '**/versions.go') }}
        restore-keys: |
          gomod-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-
          gomod-${{ runner.os }}-

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ${{ steps.goenv.outputs.go_cache }}
        key: gocache-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-${{ hashFiles('**/go.mod', '**/versions.go') }}
        restore-keys: |
          gocache-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-
          gocache-${{ runner.os }}-
