name: Setup Go
description: Setup Go using existing cache
inputs:
  go-version:
    description: The Go version to use. If unset, go.work will be used.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: ${{ !inputs.go-version && 'go.work' || '' }}
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: resolve go environment
      id: goenv
      shell: bash
      run: |
        {
          echo "go_cache=$(go env GOCACHE)"
          echo "go_modcache=$(go env GOMODCACHE)"
          echo "go_version=$(go env GOVERSION)"
        } >> "$GITHUB_OUTPUT"

    - uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ${{ steps.goenv.outputs.go_modcache }}
          ${{ steps.goenv.outputs.go_cache }}
        key: go-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-${{ hashFiles('**/go.mod', '**/versions.go') }}
        restore-keys: |
          go-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-
          go-${{ runner.os }}-
